name: Payload Extractor

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  PAYLOAD_URL: http://cdn-test-ota.blackshark.com/MBU-A0/20200320184204-mobius-ota-signed_by_xiaomi_3bb08f76617583d8b9e358f20339bade.zip
  ZIP_NAME: BlackShark
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get install wget
            sudo apt-get install p7zip-full
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            sudo -E apt-get install expect
            sudo apt update 2>/dev/null | grep packages
        
       - name: Extracting Payload
         run: |
              sudo aria2c http://tdrive.manofuranium.workers.dev/payload_dumper_tool_by_ius.zip
              sudo unzip payload_dumper_tool_by_ius.zip
              cd payload_dumper
              sudo python3 -m pip install protobuf
              sudo aria2c $PAYLOAD_URL
              sudo unzip *.zip
              sudo python3 payload_dumper.py payload.bin
              ls
              
       - name: Copying final zip
         run: |
              mkdir temp
              sudo cp -r payload_dumper/$ZIP_NAME.zip temp
              
       - name: Uploading 
         run: |
              cd temp
              expect -c "
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd /home/pfs/project/vietnam-gsi/sgsi\r\"
              set timeout -1
              send \"put $ZIP_NAME.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
       
